CREATE SCHEMA IF NOT EXISTS `devpool_erp` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `devpool_erp`;

CREATE TABLE IF NOT EXISTS `devpool_erp`.`exemplo` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(255) NOT NULL,
	`dataCriacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`));

-- COLOQUE OS SEUS COMANDOS SQL DE CRIAÇÃO DE TABELA AQUI.